language: ruby
sudo: false
rvm:
- 2.3.3
addons:
  apt:
    update: true
    packages:
    - sshpass
script:
- bundle exec jekyll build -V -t --config '_config.yml,config/_config_staging.yml'
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJ2MJD7IR432ZIUSA
    secret_access_key:
      secure: WtPsWMejLj1yZKLRtjVTGMHbg/MyPXMh5gokhmomNbMStMwy4dD5aiGMWHU+Qrh/KLgNpjGfBURfYXaO5556DCZgGvv1HE+ZErBXwiyJ/R6stGrkhgLN7gxgqP5lxVVGdF9IxlZrLbqwRXzlxr+pJUPqOkhVJZWxETBe8rc8mCs=
    region: us-east-1
    bucket: aws-website-bjc-website-cjgl5
    local-dir: _aws/
    detect_encoding: true
    on:
      repo: beautyjoy/beautyjoy.github.io
  - provider: script
    skip_cleanup: true
    script:
    - ".bin/deploy"
  - provider: script
    on:
      branch: berkeley
    skip_cleanup: true
    script:
    - bundle exec jekyll build -V -t --config '_config.yml,config/_config_berkeley.yml'
    - ".bin/copy-to-berkeley"

