language: ruby
sudo: false
rvm:
  - 2.3.3

addons:
  apt:
    update: true
    packages:
      - sshpass

script:
  - bundle exec jekyll build -V -t --config '_config.yml,config/_config_staging.yml'

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJ2MJD7IR432ZIUSA
    secret_access_key:
      secure: "ibLfiKvEjRpS8aULaOu+4+7QiUInMmDuSlQXaEQeu7nNwyLkxfLXw+ccPrVpUMERxRUR3m/ZmYfgSaQZXeEXSnwVvvIbEgLCHGTkeR2XsMl7eWlMHt8WPHltXB/q1xFy6awmg89CZDYPBWHNxoljYB5zcxaGOY5vwEq+XKp+vRo="
    region: us-east-1
    bucket: aws-website-bjc-website-cjgl5
    local-dir: _aws/
    on:
      repo: beautyjoy/beautyjoy.github.io
  - provider: script
    on:
      branch: berkeley
    skip_cleanup: true
    script:
      - bundle exec jekyll build -V -t --config '_config.yml,config/_config_berkeley.yml'
      - .bin/copy-to-berkeley
