language: ruby
sudo: false
rvm:
  - 2.3.3

addons:
  apt:
    update: true
    packages:
      - sshpass

script:
  - bundle exec jekyll build -V -t --config '_config.yml,config/_config_staging.yml'

deploy:
  - provider: script
    on:
      repo: beautyjoy/beautyjoy.github.io
    skip_cleanup: true
    script:
      - "rvm use 2.3.3 do bash .bin/deploy"
  - provider: script
    on:
      branch: berkeley
    skip_cleanup: true
    script:
    - bundle exec jekyll build -V -t --config '_config.yml,config/_config_berkeley.yml'
    - ".bin/copy-to-berkeley"

