language: ruby
sudo: false
rvm:
  - 2.3.3

addons:
  apt:
    update: true
    packages:
      - sshpass

script:
  - bundle exec jekyll build -V -t --config '_config.yml,config/_config_staging.yml'
  - bundle exec jekyll build -V -t --config '_config.yml,config/_config_berkeley.yml'


deploy:
<<<<<<< HEAD
  - provider: script
=======
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAIWKCIXYIBSD7KF7Q
    secret_access_key:
      secure: 3TqFxiYVQHo/BcM0jYQrlDGOI/P8vdP5Ycr/P1/q5tzqzUQJLf/fTQjWITRZTVi4R3GtSMYfb14nd8GkZ6MbCyV9C+drtJ12f+tg78E89pBmWjrBI8Qj8ZQqBGyru17KCGkxkRN9zcEevw87qSKTiUFWq8A9MkxaQ8AFuh8yl+4=
    bucket: aws-website-bjc-website-cjgl5
    local-dir: _aws/
    # acl: public_read
>>>>>>> 332ca551ef8dc87ddc4b85c4dad52b1e8d652f93
    on:
      repo: beautyjoy/beautyjoy.github.io
    skip_cleanup: true
    script:
      - "rvm use 2.3.3 do bash .bin/deploy"
  - provider: script
    on:
      branch: berkeley
    skip_cleanup: true
<<<<<<< HEAD
    script:
    - bundle exec jekyll build -V -t --config '_config.yml,config/_config_berkeley.yml'
    - ".bin/copy-to-berkeley"

=======
    script: bash ./.bin/copy-to-berkeley ${SCP_PASSWORD}
>>>>>>> 332ca551ef8dc87ddc4b85c4dad52b1e8d652f93
