language: ruby
sudo: false
rvm:
  - 2.3.3

addons:
  apt:
    update: true
    packages:
      - sshpass

script:
  - bundle exec jekyll build -V -t --config '_config.yml,config/_config_staging.yml'

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAIWKCIXYIBSD7KF7Q
    secret_access_key:
      secure: "L/9+qlvIM+k+/AMV1WyJ5VdN3XkQreenseAdcH5MmnTmArLIdiP3pwy344+3lXAdX8cKSs30/k3KjXQbcWi+fC2j3nOVTIESKma9myp9RgetSqqzEBS/W3TNrmEhjXgFm/UxQiDaN7C3OHvnhWQT4ksvXVEUJ9ph5I1ACNuP65E="
    region: us-east-1
    bucket: aws-website-bjc-website-cjgl5
    local-dir: _aws/
    on:
      repo: beautyjoy/beautyjoy.github.io
  - provider: script
    on:
      branch: berkeley
    skip_cleanup: true
    script:
      - bundle exec jekyll build -V -t --config '_config.yml,config/_config_berkeley.yml'
      - .bin/copy-to-berkeley
