---
title: BJC
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: UC Berkeley, Dan Garcia, Brian Harvey, Tiffany Barnes, Michael Ball, Lauren
  Mock
email: contact@bjc.berkeley.edu
description: 'The Beauty and Joy of Computing is an endorsed AP Computer Science Principles
  course that is a rigorous introduction to programming and that the ways we interact
  with and are affected by technology every day.

'
keywords: 'AP CSP, advanced placement, computer scince principles, comp sci, snap,
  programming, computing, BJC, computer science, cs10, bjcx, bjc4nyc

'
baseurl: 
url: https://beautyjoy.github.io
permalink: pretty
production_url: http://bjc.berkeley.edu
twitter_username: cspbjc
facebook_username: cspbjc
instagram_username: cspbjc
flipboard_link: https://bjc.link/computingnews
nyc_pd_page: http://cs4all.nyc/academic-programs/ap-cs-principles/
pd_interest_url: http://bjc.link/pdinterest18
markdown: kramdown
exclude:
- ".gitingore"
- Gemfile
- Gemfile.lock
- README.md
- circle.yml
- vendor
- bin
- package.json
- config
