# CircleCI artifacts format
baseurl: /0/home/ubuntu/beautyjoy.github.io/_preview
# force .html on pages to make the links work w/ Circle's artifacts
# TODO: Currently not working.
permalink: date

destination: ./_preview