s3_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
s3_bucket: aws-website-bjc-website-cjgl5
site: ../_aws
s3_endpoint: us-east-1

# TODO: fix this up.
max_age: 3600
gzip: true

cloudfront_distribution_id: E2HNU40W189IMQ

cloudfront_distribution_config:
  aliases:
    quantity: 1
    items:
      - aws.cs10.org

cloudfront_wildcard_invalidation: true
cloudfront_invalidate_root: true

treat_zero_length_objects_as_redirects: true
